name: production

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  delivery:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      # TODO: Check tag name rule

      # TODO
