name: staging

on:
  push:
    branches:
      - release/*/v*.*  # Matches release branches like release/{unit directory}/v1.0.0
  workflow_dispatch:

jobs:
  delivery:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: node ./.github/scripts/create-release-drafter-yaml.mjs
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Dummy
      - run: sleep 0.1
